//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/* SPDX-License-Identifier: Apache-2.0 */
/* Copyright(c) 2019 Wind River Systems, Inc. */

// Code generated by deepequal-gen. DO NOT EDIT.

package otherpkg

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *OtherStructWithPointers) DeepEqual(other *OtherStructWithPointers) bool {
	if other == nil {
		return false
	}

	if (in.BoolField == nil) != (other.BoolField == nil) {
		return false
	} else if in.BoolField != nil {
		if *in.BoolField != *other.BoolField {
			return false
		}
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *OtherStructWithPrimitivesOnly) DeepEqual(other *OtherStructWithPrimitivesOnly) bool {
	if other == nil {
		return false
	}

	if in.BoolField != other.BoolField {
		return false
	}

	return true
}
