//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/* SPDX-License-Identifier: Apache-2.0 */
/* Copyright(c) 2019 Wind River Systems, Inc. */

// Code generated by deepequal-gen. DO NOT EDIT.

package embedded

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *OtherStructPointer) DeepEqual(other *OtherStructPointer) bool {
	if other == nil {
		return false
	}

	if (in.BoolField == nil) != (other.BoolField == nil) {
		return false
	} else if in.BoolField != nil {
		if *in.BoolField != *other.BoolField {
			return false
		}
	}

	if (in.IntField == nil) != (other.IntField == nil) {
		return false
	} else if in.IntField != nil {
		if *in.IntField != *other.IntField {
			return false
		}
	}

	if (in.StringField == nil) != (other.StringField == nil) {
		return false
	} else if in.StringField != nil {
		if *in.StringField != *other.StringField {
			return false
		}
	}

	if (in.FloatField == nil) != (other.FloatField == nil) {
		return false
	} else if in.FloatField != nil {
		if *in.FloatField != *other.FloatField {
			return false
		}
	}

	if (in.Self == nil) != (other.Self == nil) {
		return false
	} else if in.Self != nil {
		if !in.Self.DeepEqual(other.Self) {
			return false
		}
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *OtherStructPrimitives) DeepEqual(other *OtherStructPrimitives) bool {
	if other == nil {
		return false
	}

	if in.BoolField != other.BoolField {
		return false
	}
	if in.IntField != other.IntField {
		return false
	}
	if in.StringField != other.StringField {
		return false
	}
	if in.FloatField != other.FloatField {
		return false
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *StructPrimitives) DeepEqual(other *StructPrimitives) bool {
	if other == nil {
		return false
	}

	if in.BoolField != other.BoolField {
		return false
	}
	if in.IntField != other.IntField {
		return false
	}
	if in.StringField != other.StringField {
		return false
	}
	if in.FloatField != other.FloatField {
		return false
	}
	if in.OtherStructPrimitives != other.OtherStructPrimitives {
		return false
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *StructWithEmbeddedPointerStructs) DeepEqual(other *StructWithEmbeddedPointerStructs) bool {
	if other == nil {
		return false
	}

	if !in.OtherStructPointer.DeepEqual(&other.OtherStructPointer) {
		return false
	}

	return true
}
