//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/* SPDX-License-Identifier: Apache-2.0 */
/* Copyright(c) 2019 Wind River Systems, Inc. */

// Code generated by deepequal-gen. DO NOT EDIT.

package arrays

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *Inner) DeepEqual(other *Inner) bool {
	if other == nil {
		return false
	}

	if in.Int32 != other.Int32 {
		return false
	}
	if in.String != other.String {
		return false
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *Ttest) DeepEqual(other *Ttest) bool {
	if other == nil {
		return false
	}

	if in.Bytes != other.Bytes {
		return false
	}

	if in.Strings != other.Strings {
		return false
	}

	if in.Named != other.Named {
		return false
	}

	if in.Structs != other.Structs {
		return false
	}

	return true
}
